### ISSUE TITLE
Error install via docker-compose

### ISSUE THREAD

**Issue by robben-ar** [CERTUNLP/intelmq-docker#5]
Dear,
I am trying to deploy the repository with the docker-compose.yml but I am getting errors.

```
docker-compose build
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker-compose.yml", line 12, column 3
expected <block end>, but found '<block mapping start>'
  in "./docker-compose.yml", line 35, column 4
```

Try to preload the redis images in another way but the error persists.
Do you know what it can be?
I am using the following version of the composer:

> docker-compose version 1.22.0, build f46880fe
> docker-py version: 3.4.1
> CPython version: 3.6.6
> OpenSSL version: OpenSSL 1.1.0f  25 May 2017

According to the yml validator YAMLlint has an error in one line and the .yml file is in UTF8.
What version are you using?
![image](https://user-images.githubusercontent.com/16881807/90819468-68749080-e306-11ea-9482-0a25446b74ad.png)

Thank you very much for the contribution,
Regards.-

**Comment by puckk** [comment]
Try now, and dont forget to clone bots with:

git clone https://gitlab.linti.unlp.edu.ar/certunlp/intelmq-bots.git <repodir>/volumes/intelmq-bots

**Comment by einar-lanfranco** [comment]
My fault! thank you @puckk

**Comment by robben-ar** [comment]
Perfect!
Thank you very much .. in a few days I will test the docker-compose-eg.yml version.

Regards.-
