### ISSUE TITLE
ERROR in docker-compose-eg.yml 

### ISSUE THREAD

**Issue by rzwolf** [CERTUNLP/intelmq-docker#7]
Hi!

I would like to use Elasticsearch & Grafana to configure as another output chain but I have a problem to up this docker-compose

docker-compose -f docker-compose-eg.yml up
_**ERROR: Circular dependency between elasticsearch and grafana**_

I will appreciate your help

Regards,

**Comment by einar-lanfranco** [comment]
Thank you for report this, its solved now!
