### ISSUE TITLE
Error loading bot queues information

### ISSUE THREAD

**Issue by KE-CIRT** [CERTUNLP/intelmq-docker#8]
Can't find 
![Uploading intelmq error.jpeg…]()

 - /usr/local/bin/intelmqctl
 - /opt/dev_intelmq/intelmq/bin/intemqctl.py

**Comment by einar-lanfranco** [comment]
Could you please give me more details? When this happens?

**Comment by KE-CIRT** [comment]
Solved missing files/directories  i.e    _/usr/local/bin/intelmqctl_   and  _/opt/dev_intelmq/intelmq/bin/intemqctl.py_

Still had the  same error on the web interface and e terminal executing  
> _`$docker-compose up`_ 
 

Followed  intelMQ Release 3.0.1 beta and worked fine!!!

Thank for offering help @einar-lanfranco
